---
apiVersion: v1
kind: Namespace
metadata:
  name: log-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  namespace: log-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-nginx
  template:
    metadata:
      labels:
        app: deployment-nginx
    spec:
      serviceAccountName: fluentbit-sa
      containers:
      - name: deployment-nginx
        image: 838235863925.dkr.ecr.ap-northeast-2.amazonaws.com/ubuntu-nginx:latest
        ports:
        - containerPort: 80
        volumeMounts: 
          - name: log-volume
            mountPath: /var/log/nginx
      - name: fluent-bit-sidecar
        image: fluent/fluent-bit:latest
        volumeMounts: 
          - name: log-volume
            mountPath: /var/log/nginx
          - name: config-volume
            mountPath: /fluent-bit/etc/
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: config-volume
          configMap: 
            name: fluent-bit-config
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: log-test
spec:
  selector: 
    app: deployment-nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: log-test
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     debug
        Parsers_File  parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/nginx/*.log
        Parser        container
        Tag           nginx.*
    
    [FILTER]
        Name          kubernetes
        Match         nginx.*
        Kube_URL      https://kubernetes.default.svc.cluster.local:443
        Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_CA_File  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Merge_Log     On
        Keep_Log      Off

    [OUTPUT]
        Name          cloudwatch_logs
        Match         nginx.*
        region        ap-northeast-2
        log_group_name wsi-eks-app-log
        log_stream_name nginx-sidecar
        auto_create_group true
  parsers.conf: |
    [PARSER]
        Name         container
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    Off
        Decode_Field_As json log
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-sa
  namespace: log-test
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::838235863925:role/jjw-fluentbit-sa-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules: 
  - apiGroups: [""]
    resources: 
      - pods
      - namespace
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
  - kind: ServiceAccount
    name: fluentbit-sa
    namespace: log-test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: log-test
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-nginx
            port:
              number: 80
