apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-monitoring
  namespace: monitoring-test
spec:
  selector:
    matchLabels:
      app: deployment-monitoring
  template:
    metadata:
      labels:
        app: deployment-monitoring
    spec:
      containers:
      - name: deployment-monitoring
        image: nginx:latest
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-monitoring
  namespace: monitoring-test
spec:
  type: ClusterIP
  selector:
    app: deployment-monitoring
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: monitoring-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-monitoring
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50